### ISSUE TITLE
Found this in logcat.

### ISSUE THREAD

**Issue by markubiak** [laurencedawson/reddit-sync-development#1005]
Was doing development and saw a bunch of red.  Turns out Reddit Sync can't connect to the analytics server or something.  Here's the full trace:

````
07-16 23:42:34.203  27309-27333/? E/Crashlytics﹕ Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.laurencedawson.reddit_sync.pro/settings
    d.ac: java.net.ConnectException: failed to connect to settings.crashlytics.com/127.0.0.1 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at d.bx.b(SourceFile:1391)
            at d.bx.e(SourceFile:1664)
            at d.bx.d(SourceFile:1576)
            at d.bx.c(SourceFile:1590)
            at d.an.a(SourceFile:63)
            at d.av.a(SourceFile:48)
            at d.ar.c(SourceFile:125)
            at d.c.a(SourceFile:30)
            at d.d.a(SourceFile:93)
            at d.az.run(SourceFile:13)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to settings.crashlytics.com/127.0.0.1 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:238)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
            at com.android.okhttp.Connection.connect(Connection.java:152)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:161)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:25)
            at d.bx.a(SourceFile:1912)
            at d.bx.c(SourceFile:1590)
            at d.an.a(SourceFile:63)
            at d.av.a(SourceFile:48)
            at d.ar.c(SourceFile:125)
            at d.c.a(SourceFile:30)
            at d.d.a(SourceFile:93)
            at d.az.run(SourceFile:13)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:223)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
            at com.android.okhttp.Connection.connect(Connection.java:152)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:161)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderField(DelegatingHttpsURLConnection.java:190)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:25)
            at d.bx.a(SourceFile:1912)
            at d.bx.c(SourceFile:1590)
            at d.an.a(SourceFile:63)
            at d.av.a(SourceFile:48)
            at d.ar.c(SourceFile:125)
            at d.c.a(SourceFile:30)
            at d.d.a(SourceFile:93)
            at d.az.run(SourceFile:13)
            at java.lang.Thread.run(Thread.java:818)  
````

**Comment by hzsweers** [comment]
Noticed something similar, but a different exception:

```
08-23 15:42:28.756    7384-7409/? E/Crashlytics﹕ Failed to close session user file.
    java.io.IOException: Could not rename temp file: /data/data/com.laurencedawson.reddit_sync.pro/files/.TwitterSdk/cm/com.crashlytics.sdk.android/55DA49F8036F-0001-7CE8-92D975D77CB2SessionUser.cls_temp -> /data/data/com.laurencedawson.reddit_sync.pro/files/.TwitterSdk/cm/com.crashlytics.sdk.android/55DA49F8036F-0001-7CE8-92D975D77CB2SessionUser.cls (target already exists)
            at c.an.close(SourceFile:66)
            at d.ba.a(SourceFile:718)
            at c.bb.m(SourceFile:736)
            at c.bb.b(SourceFile:66)
            at c.r.call(SourceFile:338)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at d.bl.a(SourceFile:44)
            at d.az.run(SourceFile:13)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by laurencedawson** [comment]
Strange. Closing as I can't seem to replicate and if it can't reach the server it's not the worst thing!
