### ISSUE TITLE
[Bug] Sync crashes when switching between Reddit accounts on Android Q

### ISSUE THREAD

**Issue by Tornado15550** [laurencedawson/reddit-sync-development#1989]
Description

Switching between different Reddit accounts causes the application to crash on Android 10. 

Scenario (steps to reproduce)

1. Run Android 10
2. Log into two different accounts. 
3. Switch from one account to the other. 

Result(s)

Sync will crash

Device Info

Pixel 2 XL 

Android Version: Android 10 (QPP6.190730.005) 

Sync version: 18.2 Pro

This is not reproduceable 100% of the time but it does happen frequently.

**Comment by Tornado15550** [comment]
Logcat:

FATAL EXCEPTION: pool-5-thread-3 Process: com.laurencedawson.reddit_sync.pro, PID: 11458 java.lang.IllegalStateException: Must Initialize Fabric before using singleton() at di.c.a(Fabric.java:301) at di.c.a(Fabric.java:551) at com.crashlytics.android.a.e(Crashlytics.java:191) at com.crashlytics.android.a.g(Crashlytics.java:390) at com.crashlytics.android.a.a(Crashlytics.java:233) at ay.k.a(CrashlyticsHelper.java:32) at bk.b.a(ImageManager.java:818) at bk.b$3.run(ImageManager.java:526) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)

**Comment by Tornado15550** [comment]
More logs:

<<< log_count = 26 >>> [08-24 08:07:45.632 11853:11853 E/reddit_sync.pr] Not starting debugger since process cannot load the jdwp agent.

[08-24 08:07:45.668 11853:11853 I/reddit_sync.pr] The ClassLoaderContext is a special shared library.

[08-24 08:07:45.685 11853:11853 W/reddit_sync.pr] JIT profile information will not be recorded: profile file does not exits.

[08-24 08:07:45.690 11853:11853 I/MultiDex] VM with version 2.1.0 has multidex support

[08-24 08:07:45.690 11853:11853 I/MultiDex] Installing application

[08-24 08:07:45.691 11853:11853 I/MultiDex] VM has multidex support, MultiDex support library is disabled.

[08-24 08:07:45.691 11853:11853 I/MultiDex] Installing application

[08-24 08:07:45.691 11853:11853 I/MultiDex] VM has multidex support, MultiDex support library is disabled.

[08-24 08:07:45.692 11853:11853 I/CrashlyticsInitProvider] CrashlyticsInitProvider skipping initialization

[08-24 08:07:45.701 11853:11853 D/NetworkSecurityConfig] No Network Security Config specified, using platform default

[08-24 08:07:45.722 11853:11873 W/Ads] Disabling data collection. Found google_app_id in strings.xml but Google Analytics for Firebase is missing. Remove this value or add Google Analytics for Firebase to resume data collection.

[08-24 08:07:45.735 11853:11873 W/reddit_sync.pr] Unsupported class loader

[08-24 08:07:45.741 11853:11873 W/reddit_sync.pr] Skipping duplicate class check due to unsupported classloader

[08-24 08:07:45.746 11853:11873 I/DynamiteModule] Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:20300

[08-24 08:07:45.746 11853:11873 I/DynamiteModule] Selected remote version of com.google.android.gms.ads.dynamite, version >= 20300

[08-24 08:07:45.746 11853:11873 V/DynamiteModule] Dynamite loader version >= 2, using loadModule2NoCrashUtils

[08-24 08:07:45.755 11853:11853 I/CrashlyticsCore] Initializing Crashlytics 2.6.8.32

[08-24 08:07:45.762 11853:11873 W/ChimeraDebugLogger] Singleton logger instance not set.

[08-24 08:07:45.790 11853:11873 W/reddit_sync.pr] ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/com.laurencedawson.reddit_sync.pro-6iZsPtzUd9K-1qOUtqAN3A==/base.apk2959348122:/data/app/com.laurencedawson.reddit_sync.pro-6iZsPtzUd9K-1qOUtqAN3A==/base.apk!classes2.dex2686970506]{PCL[/system/framework/org.apache.http.legacy.jar*1038351580]})

[08-24 08:07:45.797 11853:11873 W/reddit_sync.pr] Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000009/dl-AdsFdrDynamite.integ_20300000000.apk

[08-24 08:07:45.797 11853:11873 W/reddit_sync.pr] NOTE: This wastes RAM and hurts startup performance.

[08-24 08:07:45.797 11853:11873 W/reddit_sync.pr] Found duplicated class when checking oat files: 'Landroidx/browser/browseractions/BrowserActionsFallbackMenuView;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000009/dl-AdsFdrDynamite.integ_20300000000.apk and /data/app/com.laurencedawson.reddit_sync.pro-6iZsPtzUd9K-1qOUtqAN3A==/base.apk

[08-24 08:07:45.797 11853:11873 W/reddit_sync.pr]

[08-24 08:07:48.015 11853:11915 I/CrashlyticsCore] Crashlytics report upload complete: 5D60D65D016C-0001-3843-218876EAB308

[08-24 08:07:50.711 11853:11872 I/reddit_sync.pr] Waiting for a blocking GC ProfileSaver

[08-24 08:07:50.754 11853:11872 I/reddit_sync.pr] WaitForGcToComplete blocked ProfileSaver on ClassLinker for 42.331ms
